### ISSUE TITLE
[v0.4.x] Pitch / Volume export error (in some locale)

### ISSUE THREAD

**Issue by InuInu2022** [InuInu2022/NodoAme.Home#16]
from [Twitter comment](https://twitter.com/Hoami_Miruka/status/1678838653328543746).

> i having a problem with this new update
> every single output is whisper and no matter what i change in the settings still whisper, i did something wrong ?
> is whisper by default
> or it should be like that?
> also is not registering pitch
> i'm also trying older versions and all are bugging, idk why, my cevio is on 8.6
> all nodoame from 4.0 with english suport up are not working proprelly
> also not saving pitch
> or no sound emit
> i trying each version one by one until one works

**Comment by InuInu2022** [comment]
> worth to note my cevio ai is installed in disk D: for space optimize since my disk C is to little, also tested with voisona and the volume is on 0
> but at least loaded the pitch
> idk what is happening, if you want i can record my screan for you

**Comment by KimeruReru** [comment]
here the ccs and a video showing what is happening
https://drive.google.com/drive/folders/1O_XyShGBDrtZvNEDFz0vl0SFnReVfXok?usp=sharing

**Comment by InuInu2022** [comment]
https://github.com/InuInu2022/NodoAme.Home/releases/tag/v.0.4.0-alpha.130
