### ISSUE TITLE
ENG Talk Voice to JPN Song Voice not making any Sound

### ISSUE THREAD

**Issue by jikyuvox** [InuInu2022/NodoAme.Home#19]
When I use Tsurumaki Maki's English Talk Voice and convert it to Kafu's JPN Song voice, it doesn't make any noise. Even if I switch Japanese Song voices, it doesn't work.
Does the Japanese-to-English feature have a bug or is it a removed feature?

**Comment by InuInu2022** [comment]
Hello,

To use NodoAme to train English talk voice as acting guidance and speak Japanese song voice, you need to set the `EN_TO_JA` option.
Please refer to the following image to check if this setting is configured.
![image](https://github.com/InuInu2022/NodoAme.Home/assets/97830071/2f6cd2dc-1dc7-45db-8034-b0db691e7922)

**Comment by jikyusan** [comment]
Oh, now it works. Thank You so much!
